version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - pgbouncer
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  pgbouncer:
    image: edoburu/pgbouncer
    ports:
      - "6543:5432"
    env_file:
      - .env
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./userlist.txt:/etc/pgbouncer/userlist.txt:ro
