# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-15 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('email_address', models.EmailField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contact_numbers', models.CharField(max_length=130)),
                ('password', models.TextField(default='welcome')),
            ],
        ),
    ]
