# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-16 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerusers',
            name='first_name',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerusers',
            name='last_name',
            field=models.CharField(default='true', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerusers',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
